### ISSUE TITLE
Add possibility for image optimisation

### ISSUE THREAD

**Issue by zerolab** [torchbox/Willow#10]
Could piggyback off http://jpegclub.org/jpegtran/, http://pmt.sourceforge.net/pngcrush/ or similar libraries

**Comment by balazs-endresz** [comment]
Doesn't mod_pagespeed do all that already?

**Comment by zerolab** [comment]
It does indeed.

Well, I suppose it makes sense to defer it to other tools. @kaedroho?

**Comment by kaedroho** [comment]
Does mod_pagespeed run on the fly as the image is served?

**Comment by balazs-endresz** [comment]
> ngx_pagespeed speeds up your site and reduces page load time by automatically applying web performance best practices to pages and associated assets (CSS, JavaScript, images) _without requiring you to modify your existing content or workflow_

But I've also heard that it does this asynchronously, so I'm not sure if the first visitor gets the optimised version too.

**Comment by davecranwell** [comment]
I don't feel mod_pagespeed etc is the correct place for optimisation in this instance. Mod_pagespeed is a multitool for people who don't necessarily have the knowledge/time to fix issues directly.

According to Google Page Speed literally all the images uploaded by users to any given Wagtail site are wasteful (in terms of lossless optimisations possible) when served to visitors. If _all_ images are wasteful I feel we need a more deliberate approach. Given Wagtail's growing reputation for being easy and intuitive, I believe we should be addressing optimisation proactively ourselves.

**Comment by gasman** [comment]
Looks like this is what [mozjpeg](https://github.com/mozilla/mozjpeg) is designed for. There's some interest in adding support for it to Pillow, but no sign of it happening yet: https://github.com/python-pillow/Pillow/issues/539

**Comment by davecranwell** [comment]
The tool I'd normally run by hand to optimise static assets uses a combination of http://pmt.sourceforge.net/pngcrush/ (as @zerolab mentioned), http://optipng.sourceforge.net/, http://www.kokkonen.net/tjko/projects.html and http://www.lcdf.org/gifsicle/

**Comment by davecranwell** [comment]
Just a note that JPG and PNG optimisation should be the primary focus. JPG particularly as it's used for all photographs, which I'd guesstimate account for 98% of the images on our sites.

**Comment by alexfromvl** [comment]
How about making a module with automatic overstore in **webp**. Here is an excellent example https://github.com/andrefarzat/django-webp of a controller based on Django. I think it can be applied to wagtail cms and improve the overall performance of the image.
