### ISSUE TITLE
Alpha channel on PNGs discarded (image converted to JPEG).

### ISSUE THREAD

**Issue by bgrace** [torchbox/Willow#11]
Using both the released Willow==0.2 and the current head of master (3c7e8274c), while running Wagtail==1.0b1.

To reproduce: upload a PNG with transparency. Renditions will be converted to JPEG, losing the alpha channel.

Sample image input and output attached.

Input:
![good](https://cloud.githubusercontent.com/assets/821421/7243233/b99bb034-e77f-11e4-83e6-824ba581a52c.png)

Output:
![bad](https://cloud.githubusercontent.com/assets/821421/7243236/bd7598dc-e77f-11e4-85f4-23cbf75ba761.jpeg)

**Comment by kaedroho** [comment]
@bgrace This was a bug in Wagtail 1.0b1 but should be fixed in the latest master

**Comment by kaedroho** [comment]
The fix for this will be in Wagtail 1.0 beta 2
