### ISSUE TITLE
Alpha gets lost when resizing image

### ISSUE THREAD

**Issue by nwjlyons** [torchbox/Willow#18]
Hi Torchbox,

If the image is mode `P` ([8-bit pixels, mapped to any other mode using a colour palette](http://pillow.readthedocs.org/en/latest/handbook/concepts.html#modes)) the image gets [converted](https://github.com/torchbox/Willow/blob/master/willow/backends/pillow.py#L52) to `RGB` which drops the alpha channel.

With the alpha channel lost any transparency appears as solid black.

It works if the image is converted to `RGBA` but I'm just wondering does the image need to be converted at all?

**Comment by shredding** [comment]
This is leading to a serious bug with gif's because RGB changes the transparency to a tuple, e.g. `(291,0,0)`.

This will break here: https://github.com/python-pillow/Pillow/blob/master/PIL/GifImagePlugin.py#L426

`int() argument must be a string or a number, not 'tuple'`

**Comment by zerolab** [comment]
Fixed by #23
