### ISSUE TITLE
IOError at /admin/images/ cannot write mode P as JPEG

### ISSUE THREAD

**Issue by zerolab** [torchbox/Willow#4]
While testing latest Wagtail master, I encountered "IOError at /admin/images/ cannot write mode P as JPEG" with 
![torch](https://cloud.githubusercontent.com/assets/31622/6316421/3e6b3e28-ba1d-11e4-817e-b47568cb650b.png)

Full stack trace: http://pastebin.com/Mhy42zHq
PIP freeze:
```
Django==1.7.1
Pillow==2.7.0
South==1.0
Unidecode==0.04.17
Willow==0.1
argparse==1.2.1
beautifulsoup4==4.3.2
django-appconf==1.0.1
django-compressor==1.4
django-libsass==0.2
django-modelcluster==0.5
django-taggit==0.12.2
django-treebeard==2.0
html5lib==0.999
libsass==0.6.2
psycopg2==2.6
requests==2.5.1
six==1.9.0
unicodecsv==0.9.4
wagtail==0.8.5
wsgiref==0.1.2
```

Do ignore `wagtail==0.8.5` -- wagtaildemo is using the latest Wagtail master as per development instructions.

**Comment by kaedroho** [comment]
This should already be fixed in: https://github.com/torchbox/Willow/commit/0b31f85be514431c1ef4ff9c5b10b918b0de3669

**Comment by zerolab** [comment]
Ok, that fixes it.
The thumbnail is all black, but I take that is the same issue as torchbox/wagtail/issues/989
