### ISSUE TITLE
AttributeError: 'PNGImageFile' object has no attribute 'detect_faces'

### ISSUE THREAD

**Issue by mjdavies** [torchbox/Willow#42]
Afternoon all

I'm pretty sure this isn't a problem with willow, but thought I'd ask in here to see if anyone can see my mistake.

We're getting an error trying to upload images.

Server Error Report this error to your webmaster with the following information: 
Internal Server Error - 500

AttributeError: 'PNGImageFile' object has no attribute 'detect_faces'

I got the same for jpegs as well.

It's working locally in my docker setup, and I can't seem to spot the difference in the pip list output, they seem the same.

Anyone got any ideas?

[notworking.txt](https://github.com/torchbox/Willow/files/368959/notworking.txt)
[working.txt](https://github.com/torchbox/Willow/files/368958/working.txt)

**Comment by kaedroho** [comment]
Hey @mjdavies 

What version Python are you using?

Could you run the following in a Django shell on the environment that doesn't work, and paste the output here:

```python
>>> from willow.registry import registry
>>> registry._registered_image_classes
>>> registry._unavailable_image_classes
>>> registry._registered_operations
```

**Comment by mjdavies** [comment]
Hi Kaedroho

Here's that output.  No module named cv jumps out a bit!!

Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from willow.registry import registry
>>> registry._registered_image_classes
set([<class 'willow.plugins.opencv.OpenCVGrayscaleImage'>, <class 'willow.plugins.pillow.PillowImage'>, <class 'willow.plugins.opencv.OpenCVColorImage'>, <class 'willow.image.BMPImageFile'>, <class 'willow.plugins.wand.WandImage'>, <class 'willow.image.GIFImageFile'>, <class 'willow.image.PNGImageFile'>, <class 'willow.image.JPEGImageFile'>, <class 'willow.image.RGBImageBuffer'>, <class 'willow.image.RGBAImageBuffer'>])
>>> registry._unavailable_image_classes
{<class 'willow.plugins.opencv.OpenCVGrayscaleImage'>: ImportError('No module named cv',), <class 'willow.plugins.opencv.OpenCVColorImage'>: ImportError('No module named cv',)}
>>> registry._registered_operations
defaultdict(<type 'dict'>, {<class 'willow.plugins.opencv.OpenCVGrayscaleImage'>: {'get_size': <unbound method OpenCVGrayscaleImage.get_size>, 'has_alpha': <unbound method OpenCVGrayscaleImage.has_alpha>, 'detect_features': <unbound method OpenCVGrayscaleImage.detect_features>, 'has_animation': <unbound method OpenCVGrayscaleImage.has_animation>, 'detect_faces': <unbound method OpenCVGrayscaleImage.detect_faces>}, <class 'willow.image.RGBImageBuffer'>: {'get_size': <unbound method RGBImageBuffer.get_size>, 'has_alpha': <unbound method RGBImageBuffer.has_alpha>, 'has_animation': <unbound method RGBImageBuffer.has_animation>}, <class 'willow.plugins.opencv.OpenCVColorImage'>: {'get_size': <unbound method OpenCVColorImage.get_size>, 'has_alpha': <unbound method OpenCVColorImage.has_alpha>, 'has_animation': <unbound method OpenCVColorImage.has_animation>}, <class 'willow.plugins.wand.WandImage'>: {'has_alpha': <unbound method WandImage.has_alpha>, 'has_animation': <unbound method WandImage.has_animation>, 'auto_orient': <unbound method WandImage.auto_orient>, 'save_as_jpeg': <unbound method WandImage.save_as_jpeg>, 'save_as_png': <unbound method WandImage.save_as_png>, 'crop': <unbound method WandImage.crop>, 'get_size': <unbound method WandImage.get_size>, 'save_as_gif': <unbound method WandImage.save_as_gif>, 'get_wand_image': <unbound method WandImage.get_wand_image>, 'resize': <unbound method WandImage.resize>}, <class 'willow.plugins.pillow.PillowImage'>: {'has_alpha': <unbound method PillowImage.has_alpha>, 'has_animation': <unbound method PillowImage.has_animation>, 'auto_orient': <unbound method PillowImage.auto_orient>, 'save_as_jpeg': <unbound method PillowImage.save_as_jpeg>, 'save_as_png': <unbound method PillowImage.save_as_png>, 'crop': <unbound method PillowImage.crop>, 'get_size': <unbound method PillowImage.get_size>, 'get_pillow_image': <unbound method PillowImage.get_pillow_image>, 'save_as_gif': <unbound method PillowImage.save_as_gif>, 'resize': <unbound method PillowImage.resize>}, <class 'willow.image.RGBAImageBuffer'>: {'get_size': <unbound method RGBAImageBuffer.get_size>, 'has_alpha': <unbound method RGBAImageBuffer.has_alpha>, 'has_animation': <unbound method RGBAImageBuffer.has_animation>}})

**Comment by kaedroho** [comment]
Thanks @mjdavies 

Yep, it looks like that may be the issue. Installing OpenCV can be a little tricky as it isn't pip-installable. You can find docs for installing it in Wagtail though: http://docs.wagtail.io/en/v1.5.2/advanced_topics/images/feature_detection.html#setup

It looks like there's a bug in Willow's error handling as this should've raised that ``ImportError('No module named cv',)`` error at the point you were accessing the ``detect_faces`` method. Which version of Python are you using?

**Comment by mjdavies** [comment]
Hi Kaedroho

Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2

I've just built a docker image for our app installing everything with pip and that has worked, which is a bit nuts!!

**Comment by mjdavies** [comment]
ok. moving on

I've uninstalled python-opencv, then reinstalled it.

I'm uploading the output of those commands again Kaedroho, ouput2.txt as I'm still getting the same error as before, but cv is present now.

[output2.txt](https://github.com/torchbox/Willow/files/369140/output2.txt)

**Comment by mjdavies** [comment]
Hello everyone, anyone got any ideas about this?
