### ISSUE TITLE
Need ability to try or specify alternate face detection

### ISSUE THREAD

**Issue by mhnbcu** [torchbox/Willow#5]
We have lots of standing full height (head to feet) photos where the faces are detected better with "haarscascade_frontface_alt_tree.xml". Currently, "haarscascade_frontalface_alt2.xml" is hardcoded and results in the focal point rect being larger than the image in many cases.

For what its worth I'm not sure if this need is shared by others but since we have over 150,000 images I imagine having some configuration options and/or ability to specify fall backs would be good. 

Does this make sense in any way?

**Comment by kaedroho** [comment]
Thanks!

I'm thinking this could be solved by an extra keyword argument to the ``detect_faces`` operation.

Example:

```
# Using an absolute path to the file will make it look in the filesystem
image.detect_faces(cascade_filename=settings.PROJECT_ROOT + '/my_cascade_file.xml')

# Using just the filename will make it look in willows face_detection directory
# https://github.com/torchbox/Willow/tree/master/willow/backends/face_detection
# We only include one cascade file, but we can add more if they're useful
image.detect_faces(cascade_filename='haarcascade_frontalface_alt2.xml')
```

How does that sound?

**Comment by mhnbcu** [comment]
@kaedroho yes the extra keyword argument to the `detect_faces` operation would be good if you feel it is sufficient to surface the API in the wagtail.wagtailimages so it can be used by the Image model or a subclass of it. 

To illustrate the end goal here is an example:

```
from wagtail.wagtailimages.models import Image

class CustomImage(Image):

    RED_CARPET_SHOT = 'red_carpet.xml'
    CLOSE_UP_SHOT = 'close_up.xml'
    MOVIE_STILL_SHOT = 'movie_still.xml'
    SELFIE_SHOT = 'selfie.xml'

    FEATURE_DETECTOR_CHOICES = (
        (RED_CARPET_SHOT, 'Red Carpet'),
        (CLOSE_UP_SHOT, 'Close Up'),
        (MOVIE_STILL_SHOT, 'Movie Still'),
        (SELFIE_SHOT, 'Selfie'),
    )

    feature_detector = models.CharField(max_length=50, \
        choices=FEATURE_DETECTOR_CHOICES, default=RED_CARPET_SHOT, \
        help_text='Type of photo/camera shot', verbose_name='Shot Type')

    admin_form_fields = Image.admin_form_fields + (
        'feature_detector',
    )
    
    def get_feature_detector(self):
        return self.feature_detector
```

Then in `image_feature_detection` from `wagtail.wagtailimages.models` something like the following could be possible:

```
def image_feature_detection(sender, instance, **kwargs):
    if getattr(settings, 'WAGTAILIMAGES_FEATURE_DETECTION_ENABLED', False):
        # Make sure the image doesn't already have a focal point
        if not instance.has_focal_point():
            # Set the focal point
            suggested_focal_point = instance.get_suggested_focal_point( \
                cascade_filename=instance.get_feature_detector())
            instance.set_focal_point(suggested_focal_point)
````

What do you think about this? Any suggestions are welcome!
